/* -- EEK! I wouldn't uncomment this -- as hackable as MUSE is, this probably
      would be a very, VERY bad idea.  Don't do it.
DO_NUM("allow_exec",allow_exec)
DO_STR("exec_config",exec_config)
DO_STR("exec_shell",exec_shell)
DO_STR("exec_shellav0",exec_shellav0)
*/

#ifndef DEFDBREF
#define DEFDBREF
typedef long dbref;             /* offset into db */
#endif


DO_STR("dbinfo_chan",dbinfo_chan)
DO_STR("dc_chan",dc_chan)
DO_NUM("allow_create",allow_create)
DO_STR("muse_name",muse_name)
DO_REF("player_start",player_start)
DO_REF("guest_start",guest_start)
/*DO_REF("limbo",limbo)*/
DO_REF("default_room",default_room)
DO_STR("start_quota",start_quota)
DO_NUM("initial_credits",initial_credits)
DO_NUM("allowance",allowance)
DO_STR("start_quota",start_quota)
DO_LNG("default_idletime",default_idletime)
DO_LNG("guest_boot_time",guest_boot_time)
DO_NUM("number_guests",number_guests)
DO_STR("guest_prefix",guest_prefix)
DO_STR("guest_alias_prefix",guest_alias_prefix)
DO_STR("guest_description",guest_description)
DO_LNG("max_pennies",max_pennies)
DO_NUM("inet_port",inet_port)
DO_NUM("fixup_interval",fixup_interval)
DO_NUM("dump_interval",dump_interval)
/*DO_NUM("fight_interval",fight_interval)*/
DO_NUM("garbage_chunk",garbage_chunk)
DO_NUM("max_output",max_output)
DO_NUM("max_input",max_input)
DO_NUM("command_time_msec",command_time_msec)
DO_NUM("command_burst_size",command_burst_size)
DO_NUM("commands_per_time",commands_per_time)
DO_STR("bad_object_doomsday",bad_object_doomsday)
DO_STR("default_doomsday",default_doomsday)
DO_NUM("warning_chunk", warning_chunk)
DO_NUM("warning_bonus",warning_bonus)
DO_STR("def_db_in",def_db_in)
DO_STR("def_db_out",def_db_out)
DO_STR("stdout_logfile",stdout_logfile)
DO_STR("wd_logfile",wd_logfile)
DO_STR("muse_pid_file",muse_pid_file)
DO_STR("wd_pid_file",wd_pid_file)
DO_STR("create_msg_file",create_msg_file)
DO_STR("motd_msg_file",motd_msg_file)
DO_STR("welcome_msg_file",welcome_msg_file)
DO_STR("guest_msg_file",guest_msg_file)
DO_STR("register_msg_file",register_msg_file)
DO_STR("leave_msg_file",leave_msg_file)
DO_STR("guest_lockout_file",guest_lockout_file)
DO_STR("welcome_lockout_file",welcome_lockout_file)
DO_NUM("enable_lockout",enable_lockout)
DO_REF("root",root)
DO_NUM("thing_cost",thing_cost)
DO_NUM("exit_cost",exit_cost)
DO_NUM("room_cost",room_cost)
DO_NUM("robot_cost",robot_cost)
DO_NUM("univ_cost",univ_cost)
DO_NUM("channel_cost",channel_cost)
DO_NUM("link_cost",link_cost)
DO_NUM("find_cost",find_cost)
DO_NUM("search_cost",search_cost)
DO_NUM("page_cost",page_cost)
DO_NUM("announce_cost",announce_cost)
DO_NUM("queue_cost",queue_cost)
DO_NUM("queue_loss",queue_loss)
DO_NUM("max_queue",max_queue)
DO_NUM("channel_name_limit",channel_name_limit)
DO_NUM("player_name_limit",player_name_limit)
DO_NUM("player_reference_limit",player_reference_limit)
DO_NUM("announce_guests", announce_guests)     /* 1 to announce guest connections */
DO_NUM("announce_connects", announce_connects) /* 1 to broadcast all connections */

