/* -- EEK! I wouldn't uncomment this -- as hackable as MUSE is, this probably
      would be a very, VERY bad idea.  Don't do it.
DO_NUM("allow_exec",allow_exec)
DO_STR("exec_config",exec_config)
DO_STR("exec_shell",exec_shell)
DO_STR("exec_shellav0",exec_shellav0)
*/

#ifndef DEFDBREF
#define DEFDBREF
typedef long dbref;             /* offset into db */
#endif


DO_NUM("allow_create",allow_create)
DO_STR("muse_name",muse_name)
DO_REF("player_start",player_start)
DO_REF("guest_start",guest_start)
/*DO_REF("limbo",limbo)*/
DO_REF("default_room",default_room)
DO_STR("start_quota",start_quota)
DO_NUM("initial_credits",initial_credits)
DO_NUM("allowance",allowance)
DO_LNG("default_idletime",default_idletime)
DO_LNG("guest_boot_time",guest_boot_time)
DO_NUM("number_guests",number_guests)
DO_STR("guest_prefix",guest_prefix)
DO_STR("guest_alias_prefix",guest_alias_prefix)
DO_STR("guest_description",guest_description)
DO_LNG("max_pennies",max_pennies)
DO_NUM("inet_port",inet_port)
DO_NUM("fixup_interval",fixup_interval)
DO_NUM("dump_interval",dump_interval)
/*DO_NUM("fight_interval",fight_interval)*/
DO_NUM("garbage_chunk",garbage_chunk)
DO_NUM("max_output",max_output)
DO_NUM("max_output_pueblo",max_output_pueblo)
DO_NUM("max_input",max_input)
DO_NUM("command_time_msec",command_time_msec)
DO_NUM("command_burst_size",command_burst_size)
DO_NUM("commands_per_time",commands_per_time)
DO_STR("bad_object_doomsday",bad_object_doomsday)
DO_STR("default_doomsday",default_doomsday)
DO_NUM("warning_chunk", warning_chunk)
DO_NUM("warning_bonus",warning_bonus)
DO_STR("def_db_in",def_db_in)
DO_STR("def_db_out",def_db_out)
DO_STR("stdout_logfile",stdout_logfile)
DO_STR("wd_logfile",wd_logfile)
DO_STR("muse_pid_file",muse_pid_file)
DO_STR("wd_pid_file",wd_pid_file)
DO_STR("create_msg",create_msg)
DO_STR("motd_msg",motd_msg)
DO_REF("motd_msg_player",motd_msg_player)
DO_STR("welcome_msg",welcome_msg)
DO_STR("guest_msg",guest_msg)
DO_STR("register_msg",register_msg)
DO_STR("leave_msg",leave_msg)
DO_NUM("guest_enabled",guest_enabled)
DO_STR("guest_lockout_msg",guest_lockout_msg)
DO_STR("welcome_lockout_msg",welcome_lockout_msg)
DO_NUM("maintenance_level",maintenance_level)
DO_STR("maintenance_msg",maintenance_msg)
DO_REF("root",root)
DO_NUM("thing_cost",thing_cost)
DO_NUM("exit_cost",exit_cost)
DO_NUM("room_cost",room_cost)
DO_NUM("robot_cost",robot_cost)
DO_NUM("univ_cost",univ_cost)
DO_NUM("channel_cost",channel_cost)
DO_NUM("link_cost",link_cost)
DO_NUM("find_cost",find_cost)
DO_NUM("search_cost",search_cost)
DO_NUM("page_cost",page_cost)
DO_NUM("announce_cost",announce_cost)
DO_NUM("queue_cost",queue_cost)
DO_NUM("queue_loss",queue_loss)
DO_NUM("max_queue",max_queue)
DO_NUM("channel_name_limit",channel_name_limit)
DO_NUM("player_name_limit",player_name_limit)
DO_NUM("player_reference_limit",player_reference_limit)
DO_NUM("announce_guests", announce_guests)     /* 1 to announce guest connections */
DO_NUM("announce_connects", announce_connects) /* 1 to broadcast all connections */
DO_STR("flushed_message",flushed_message)
DO_STR("online_message",online_message)
DO_STR("reboot_message",reboot_message)
DO_STR("shutdown_message",shutdown_message)
DO_STR("lockout_message",lockout_message)
DO_STR("first_login",first_login)
DO_NUM("min_idle",min_idle)
DO_NUM("max_idle",max_idle)
DO_NUM("num_welcome_messages",num_welcome_messages)
DO_STR("loginstats_file",loginstats_file)
DO_NUM("loginstats_max_backups",loginstats_max_backups)
DO_NUM("max_emails_per_day",max_emails_per_day)
DO_NUM("email_cooldown",email_cooldown)
DO_NUM("max_email_length",max_email_length)
DO_STR("smtp_server",smtp_server)
DO_NUM("smtp_port",smtp_port)
DO_NUM("smtp_use_ssl",smtp_use_ssl)
DO_STR("smtp_username",smtp_username)
DO_STR("smtp_password",smtp_password)
DO_STR("smtp_from",smtp_from)

