/* credits.h */
/* $Id: credits.h,v 1.13 1997/02/10 23:43:09 mu-net org Exp $ */

/*
     This code began as TinyMUSH v1.5.  It has been heavily modified
     since that time by the following people:

	Bobby Newmark	newmark@mu-net.org
	NetRunner	kotcher@cis.ohio-state.edu
	shkoo		shkoo@chezmoto.ai.mit.edu
	Erk		erk@chezmoto.ai.mit.edu
	Michael		michael@chezmoto.ai.mit.edu

     The following variable defines the current version number.
*/

/*-------------------------------------------------------------------------*
   Version format: 2.YY.MM.DD beta X
     2    = major version (always 2)
     YY   = 2-digit year
     MM   = month (1-12)
     DD   = day (1-31)
     X    = commit number for that day (1, 2, 3, ...)

   The version is automatically updated by the pre-commit hook
   (scripts/update-version.sh). Do not edit BASE_VERSION manually.
 *-------------------------------------------------------------------------*/

/* AUTO-GENERATED by pre-commit hook - do not edit manually */
#define BASE_VERSION	"|W+DeMUSE 2.26.3.14 beta 1|"

/* This is the database version number.  Version numbers have been introduced
   into the database to facilitate automatic database restructuring */
#define  DB_VERSION	14
