/* mariadb_auth.h - Token-based authentication via MariaDB
 *
 * ============================================================================
 * MODERNIZATION NOTES (2026)
 * ============================================================================
 * Validates one-time login tokens generated by the PHP web layer.
 * Tokens are stored in the auth_tokens table with a 60-second expiry.
 * The PHP layer handles all password operations — netmuse never sees
 * plaintext passwords.
 *
 * Also manages the universe_players mapping (account_id → player_dbref).
 *
 * SAFETY:
 * - All SQL uses mysql_real_escape_string to prevent injection
 * - Connection checked before every operation
 */

#ifndef _MARIADB_AUTH_H_
#define _MARIADB_AUTH_H_

#include "config.h"

#ifdef USE_MARIADB

/* ============================================================================
 * TOKEN VALIDATION
 * ============================================================================ */

/*
 * mariadb_auth_validate_token - Validate and consume a one-time login token
 *
 * Checks the auth_tokens table for a matching, unexpired, unconsumed token.
 * On success, marks the token as consumed and returns the account_id.
 *
 * @param token  The token string (64-char hex)
 * @return account_id on success, 0 on failure (invalid/expired/consumed)
 */
long mariadb_auth_validate_token(const char *token);

/*
 * mariadb_auth_cleanup_expired - Delete expired and consumed tokens
 *
 * Called periodically from timer.c to keep the auth_tokens and
 * email_verify_tokens tables clean.
 */
void mariadb_auth_cleanup_expired(void);

/* ============================================================================
 * ACCOUNT-PLAYER MAPPING
 * ============================================================================ */

/*
 * mariadb_auth_find_player - Find the player dbref for an account in a universe
 *
 * @param account_id  Account ID to look up
 * @param universe_id Universe ID (0 for lobby/default in Phase 1b)
 * @return player dbref on success, NOTHING (-1) if no mapping exists
 */
dbref mariadb_auth_find_player(long account_id, int universe_id);

/*
 * mariadb_auth_link_player - Link an account to a player in a universe
 *
 * Creates a row in universe_players. Used after auto-creating a player
 * on first token login.
 *
 * @param account_id  Account ID
 * @param universe_id Universe ID (0 for Phase 1b)
 * @param player      Player dbref
 * @return 1 on success, 0 on failure
 */
int mariadb_auth_link_player(long account_id, int universe_id, dbref player);

/*
 * mariadb_auth_get_username - Get the username for an account
 *
 * @param account_id  Account ID
 * @param buf         Output buffer for username
 * @param buflen      Size of output buffer
 * @return 1 on success, 0 if account not found
 */
int mariadb_auth_get_username(long account_id, char *buf, size_t buflen);

#else /* !USE_MARIADB */

/* Stub functions — server requires MariaDB so these should never be reached */
static inline long mariadb_auth_validate_token(
    const char *t __attribute__((unused))) { return 0; }
static inline void mariadb_auth_cleanup_expired(void) { }
static inline dbref mariadb_auth_find_player(
    long a __attribute__((unused)),
    int u __attribute__((unused))) { return -1; }
static inline int mariadb_auth_link_player(
    long a __attribute__((unused)),
    int u __attribute__((unused)),
    dbref p __attribute__((unused))) { return 0; }
static inline int mariadb_auth_get_username(
    long a __attribute__((unused)),
    char *b __attribute__((unused)),
    size_t l __attribute__((unused))) { return 0; }

#endif /* USE_MARIADB */

#endif /* _MARIADB_AUTH_H_ */
