/* mariadb_auth.c - Token-based authentication via MariaDB
 *
 * ============================================================================
 * MODERNIZATION NOTES (2026)
 * ============================================================================
 * Validates one-time login tokens generated by the PHP web layer.
 * Manages the account-to-player mapping in universe_players.
 *
 * SAFETY:
 * - All string inputs escaped with mysql_real_escape_string
 * - Connection validated before every query
 * - Tokens consumed (deleted) on successful validation
 */

#ifdef USE_MARIADB

/* Suppress conversion warnings from MariaDB headers */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wconversion"
#pragma GCC diagnostic ignored "-Wsign-conversion"
#include <mysql.h>
#pragma GCC diagnostic pop

#include "config.h"
#include "db.h"
#include "externs.h"
#include "mariadb.h"
#include "mariadb_auth.h"

#include <stdio.h>
#include <string.h>

/* ============================================================================
 * TOKEN VALIDATION
 * ============================================================================ */

/*
 * mariadb_auth_validate_token - Validate and consume a one-time login token
 *
 * Atomically claims the token by flipping consumed 0 -> 1 in a single
 * UPDATE keyed on (token, consumed=0, expires_at>NOW()). The row-level
 * write lock means only one concurrent caller can flip the flag; losers
 * see mysql_affected_rows() == 0 and bail out, preventing token replay.
 *
 * Once the row is claimed, the account_id is safe to fetch — no other
 * caller can win a second SELECT against this token. The DELETE that
 * follows is bookkeeping; even if it fails, the token is no longer
 * usable because consumed=1 is now persistent and the validity gate
 * also checks consumed=0.
 *
 * RETURNS: account_id on success, 0 on failure
 */
long mariadb_auth_validate_token(const char *token)
{
    MYSQL *conn;
    MYSQL_RES *result;
    MYSQL_ROW row;
    char escaped_token[129];
    char query[512];
    long account_id = 0;

    /* Reject anything that cannot be a valid token BEFORE escaping it.
     * auth_tokens.token is VARCHAR(64), so a longer string can never
     * match a row anyway — and, critically, escaped_token[129] is sized
     * for 2*64+1.  mysql_real_escape_string() can write up to
     * 2*strlen(token)+1 bytes, so without this length gate an
     * unauthenticated client sending "connect token:<long string>" would
     * smash this fixed stack buffer (remote pre-auth overflow). */
    if (!token || !*token || strlen(token) > 64) {
        return 0;
    }

    conn = (MYSQL *)mariadb_get_connection();
    if (!conn) {
        return 0;
    }

    mysql_real_escape_string(conn, escaped_token, token,
                             (unsigned long)strlen(token));

    /* Atomic claim: flip consumed 0 -> 1 only if token is still valid.
     * The row-level lock InnoDB takes here serializes concurrent
     * validators — exactly one wins per token. */
    snprintf(query, sizeof(query),
             "UPDATE auth_tokens SET consumed = 1 "
             "WHERE token = '%s' AND consumed = 0 AND expires_at > NOW()",
             escaped_token);

    if (mysql_query(conn, query)) {
        fprintf(stderr, "MariaDB auth: token claim failed: %s\n",
                mysql_error(conn));
        return 0;
    }

    /* If we didn't win the race (or the token is invalid/expired),
     * bail out without revealing anything. */
    if (mysql_affected_rows(conn) != 1) {
        return 0;
    }

    /* Token is now atomically claimed by us; safe to read the account. */
    snprintf(query, sizeof(query),
             "SELECT account_id FROM auth_tokens "
             "WHERE token = '%s' AND consumed = 1",
             escaped_token);

    if (mysql_query(conn, query)) {
        fprintf(stderr, "MariaDB auth: token lookup failed: %s\n",
                mysql_error(conn));
        return 0;
    }

    result = mysql_store_result(conn);
    if (!result) {
        return 0;
    }

    row = mysql_fetch_row(result);
    if (row && row[0]) {
        account_id = atol(row[0]);
    }
    mysql_free_result(result);

    if (account_id > 0) {
        /* Bookkeeping delete — the token is already consumed; this
         * just keeps the table tidy until the periodic cleanup runs.
         * Failure here does not affect correctness. */
        snprintf(query, sizeof(query),
                 "DELETE FROM auth_tokens WHERE token = '%s'",
                 escaped_token);
        mysql_query(conn, query);
    }

    return account_id;
}

/*
 * mariadb_auth_cleanup_expired - Delete expired and consumed tokens
 *
 * Called periodically from timer.c to keep tables clean.
 */
void mariadb_auth_cleanup_expired(void)
{
    MYSQL *conn;

    conn = (MYSQL *)mariadb_get_connection();
    if (!conn) {
        return;
    }

    /* Clean up expired/consumed auth tokens */
    mysql_query(conn,
        "DELETE FROM auth_tokens WHERE expires_at < NOW() OR consumed = 1");

    /* Clean up expired email verification tokens */
    mysql_query(conn,
        "DELETE FROM email_verify_tokens WHERE expires_at < NOW()");

    /* Clean up expired password reset tokens */
    mysql_query(conn,
        "DELETE FROM password_reset_tokens WHERE expires_at < NOW()");

    /* Prune stale rate-limit rows.  rate_limit_check() only ever inserts
     * or resets a counter in place, so without this sweep the table grows
     * unbounded (one permanent row per distinct IP / username / email ever
     * seen).  One day comfortably exceeds the longest active window
     * (currently 1 hour), so this never drops a row an in-flight limit
     * still relies on.  idx_window_start makes the range scan cheap. */
    mysql_query(conn,
        "DELETE FROM rate_limit WHERE window_start < NOW() - INTERVAL 1 DAY");
}

/* ============================================================================
 * ACCOUNT-PLAYER MAPPING
 * ============================================================================ */

/*
 * mariadb_auth_find_player - Find the player dbref for an account in a universe
 *
 * RETURNS: player dbref on success, NOTHING if no mapping exists
 */
dbref mariadb_auth_find_player(long account_id, int universe_id)
{
    MYSQL *conn;
    MYSQL_RES *result;
    MYSQL_ROW row;
    char query[256];
    dbref player = NOTHING;

    conn = (MYSQL *)mariadb_get_connection();
    if (!conn) {
        return NOTHING;
    }

    snprintf(query, sizeof(query),
             "SELECT player_dbref FROM universe_players "
             "WHERE account_id = %ld AND universe_id = %d",
             account_id, universe_id);

    if (mysql_query(conn, query)) {
        fprintf(stderr, "MariaDB auth: find_player query failed: %s\n",
                mysql_error(conn));
        return NOTHING;
    }

    result = mysql_store_result(conn);
    if (!result) {
        return NOTHING;
    }

    row = mysql_fetch_row(result);
    if (row && row[0]) {
        player = atol(row[0]);
    }
    mysql_free_result(result);

    return player;
}

/*
 * mariadb_auth_link_player - Link an account to a player in a universe
 *
 * Creates a row in universe_players. Used after auto-creating a player
 * on first token login.
 *
 * RETURNS: 1 on success, 0 on failure
 */
int mariadb_auth_link_player(long account_id, int universe_id, dbref player)
{
    MYSQL *conn;
    char query[256];

    conn = (MYSQL *)mariadb_get_connection();
    if (!conn) {
        return 0;
    }

    snprintf(query, sizeof(query),
             "INSERT INTO universe_players (account_id, universe_id, player_dbref) "
             "VALUES (%ld, %d, %" DBREF_FMT ")",
             account_id, universe_id, player);

    if (mysql_query(conn, query)) {
        fprintf(stderr, "MariaDB auth: link_player failed: %s\n",
                mysql_error(conn));
        return 0;
    }

    return 1;
}

/*
 * mariadb_auth_get_username - Get the username for an account
 *
 * RETURNS: 1 on success, 0 if account not found
 */
int mariadb_auth_get_username(long account_id, char *buf, size_t buflen)
{
    MYSQL *conn;
    MYSQL_RES *result;
    MYSQL_ROW row;
    char query[256];

    if (!buf || buflen < 1) {
        return 0;
    }
    buf[0] = '\0';

    conn = (MYSQL *)mariadb_get_connection();
    if (!conn) {
        return 0;
    }

    snprintf(query, sizeof(query),
             "SELECT username FROM accounts WHERE account_id = %ld",
             account_id);

    if (mysql_query(conn, query)) {
        fprintf(stderr, "MariaDB auth: get_username failed: %s\n",
                mysql_error(conn));
        return 0;
    }

    result = mysql_store_result(conn);
    if (!result) {
        return 0;
    }

    row = mysql_fetch_row(result);
    if (row && row[0]) {
        strncpy(buf, row[0], buflen - 1);
        buf[buflen - 1] = '\0';
        mysql_free_result(result);
        return 1;
    }

    mysql_free_result(result);
    return 0;
}

#endif /* USE_MARIADB */
